version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    expose:
      - 5432
  app:
    build: .
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      NODE_ENV: development
    volumes:
      - ./:/src/
    depends_on:
      - postgres
